# Generated by Django 5.1 on 2024-09-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_product_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prix_total',
        ),
    ]
