# Generated by Django 5.1 on 2024-09-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_delivery_address_alter_cart_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='order',
            name='prix_total',
            field=models.FloatField(default=0.0),
        ),
    ]
