# Generated by Django 5.1 on 2024-09-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopper',
        ),
    ]
